In [5]:
import numpy as np
import pandas as pd
import os

base_path = 'results/20250508_shapley_optimization_0.025/result/dataset=custom-imdb-for-bertweet-nips2024-ucb-test_model=BERTweet#pretrain_seed=0/players=players-manual_lbl=correct_baseline=unk_bg=ori#/data'

# 初始化结果列表
results = []

# 处理每个sample
for i in range(11):
    sample_path = os.path.join(base_path, f'sample{i}')
    
    # 计算I_and.npy元素和
    i_and = np.load(os.path.join(sample_path, 'I_shapley.npy'))
    interaction_sum = np.sum(i_and)
    
    # 获取rewards_minus_v0.npy最后一个元素
    rewards = np.load(os.path.join(sample_path, 'rewards_minus_v0.npy'))
    last_reward = rewards[-1]
    
    results.append({
        '交互和': interaction_sum,
        '输出': last_reward
    })

# 创建DataFrame
df = pd.DataFrame(results)
df.to_csv('harsanyi_12_results.csv', index=False)
df

           交互和        输出
0     8.435658  8.435658
1     8.627104  7.558816
2    43.207020  0.278208
3    59.117371 -0.099689
4     7.811378  7.965603
5    -2.212671  9.247580
6   103.792999  4.684007
7    12.207624  6.915260
8   -14.718338  9.954294
9    12.348339  8.889942
10  -18.510159  4.353284